linters:
  disable-all: true
  enable:
  - deadcode
  - gocritic
  - gocyclo
  - gofmt
  - golint
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - staticcheck
  - structcheck
  - unparam
  - unused
  - varcheck
